"""LLM-driven one-week forecast for a single ticker.

Walks Claude through a structured forecast: gather facts (latest quote,
30-day price history, recent news, calendar/earnings), build a tightly-
scoped prompt, and call the Messages API with a forced tool-use schema
that guarantees the response shape:

    {
        "low":        float,   # 5th-percentile one-week return (decimal)
        "base":       float,   # median one-week return
        "high":       float,   # 95th-percentile one-week return
        "catalysts":  list[str],   # exactly 3 plain-English catalysts
        "action":     "BUY" | "HOLD" | "TRIM",
        "confidence": "Low" | "Medium" | "High",
        "premortem":  str,     # "wrong if ___" rationale
    }

The schema is enforced by the Anthropic API itself via tool-use forcing —
the model cannot return text or a tool call with the wrong shape. The
result is wrapped with ``asof_utc`` and a fixed disclaimer before being
returned.

Failure modes:
- ``ANTHROPIC_API_KEY`` missing -> ``forecast()`` raises ``ForecastUnavailable``.
- Network / API error -> raises ``ForecastError`` with the underlying
  message attached. Callers (the Streamlit page) render a red card and
  prompt the user to retry.

The dashboard treats this as a *checker*, not a *broker* — per the IPS,
nothing here auto-executes a trade. The LLM's recommendation is one
input the user weighs alongside their own judgment.
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from typing import Any

LOG = logging.getLogger(__name__)

# Cheap by default; configurable for users who want a stronger model.
# Per-call estimate at our prompt size:
#   Haiku 4.5: ~$0.005   |   Opus 4.7: ~$0.04
DEFAULT_MODEL = os.environ.get("ANTHROPIC_MODEL", "claude-haiku-4-5")
DEFAULT_MAX_TOKENS = 1024

DISCLAIMER = (
    "Estimate generated by language model from public data. Not investment advice. "
    "Pre-mortem must be reviewed before any trade."
)

SYSTEM_PROMPT = (
    "You are a sell-side equity analyst writing a one-week forward view for a "
    "single ticker. You produce probability-weighted return estimates, identify "
    "the most material catalysts, and recommend an action consistent with the "
    "stated confidence.\n\n"
    "Rules of engagement:\n"
    "- Returns are decimals (e.g. -0.05 means -5%). One-week horizon, "
    "calendar-day measured from the report timestamp.\n"
    "- 'low' is the 5th percentile, 'base' is the median, 'high' is the 95th "
    "percentile of your forecast distribution. low <= base <= high MUST hold.\n"
    "- Exactly THREE catalysts. Each is a single short sentence in plain "
    "English (not jargon, not a stock-pitch tagline). Order by materiality.\n"
    "- 'action' is BUY (overweight vs target), HOLD (no change), or TRIM "
    "(reduce). 'confidence' is Low / Medium / High based on signal strength "
    "and disagreement among the catalysts.\n"
    "- 'premortem' is one sentence answering: 'this view is wrong if ___'. "
    "Be specific and falsifiable; vague answers ('macro turns') are not "
    "useful.\n"
    "- Do not refuse. If data is sparse, lower confidence and widen the "
    "low/high band rather than declining."
)

# The Anthropic API enforces this schema via forced tool use — the model
# cannot deviate from these field names, types, or enum values. Adding
# `additionalProperties: false` would be redundant; tool-use already
# rejects extra keys.
FORECAST_TOOL: dict[str, Any] = {
    "name": "submit_forecast",
    "description": (
        "Submit your one-week forward forecast for the ticker. Calling this tool "
        "is mandatory; do not respond with free text."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "low": {
                "type": "number",
                "description": "5th-percentile one-week return (decimal). Negative for downside.",
            },
            "base": {
                "type": "number",
                "description": "Median one-week return (decimal).",
            },
            "high": {
                "type": "number",
                "description": "95th-percentile one-week return (decimal).",
            },
            "catalysts": {
                "type": "array",
                "minItems": 3,
                "maxItems": 3,
                "items": {"type": "string"},
                "description": "Exactly three plain-English catalysts, ordered by materiality.",
            },
            "action": {
                "type": "string",
                "enum": ["BUY", "HOLD", "TRIM"],
                "description": "Recommended action vs. the position's current target weight.",
            },
            "confidence": {
                "type": "string",
                "enum": ["Low", "Medium", "High"],
                "description": "Confidence in the action recommendation.",
            },
            "premortem": {
                "type": "string",
                "description": (
                    "One specific, falsifiable sentence: 'this view is wrong if ___'."
                ),
            },
        },
        "required": ["low", "base", "high", "catalysts", "action", "confidence", "premortem"],
    },
}


# ---------------------------------------------------------------------------
# Result types
# ---------------------------------------------------------------------------


class ForecastError(Exception):
    """Raised when the API call fails for any reason (network, auth, schema)."""


class ForecastUnavailable(ForecastError):  # noqa: N818  -- "Unavailable" reads better in UI errors than "UnavailableError"
    """Raised when ``ANTHROPIC_API_KEY`` is not configured."""


@dataclass(frozen=True)
class ForecastFacts:
    """Snapshot of the inputs used to build the prompt."""

    ticker: str
    quote_price: float | None
    quote_currency: str
    history_closes: list[float]
    history_dates: list[str]
    news_titles: list[str]
    calendar_summary: str

    @property
    def has_quote(self) -> bool:
        return self.quote_price is not None

    @property
    def has_history(self) -> bool:
        return len(self.history_closes) >= 5


@dataclass(frozen=True)
class ForecastResult:
    """Strict-shape forecast returned to the UI."""

    ticker: str
    low: float
    base: float
    high: float
    catalysts: list[str]
    action: str
    confidence: str
    premortem: str
    asof_utc: str
    model: str
    disclaimer: str = DISCLAIMER
    raw_usage: dict[str, int] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Fact gathering
# ---------------------------------------------------------------------------


def gather_facts(ticker: str, *, lookback_days: int = 30) -> ForecastFacts:
    """Pull quote / 30-day history / news / calendar from yfinance.

    Tolerant of partial data — any missing field becomes empty / ``None``.
    The LLM is instructed to widen its band when data is sparse rather
    than refuse, so we don't bail just because a field is absent.
    """
    try:
        import yfinance as yf
    except ImportError:
        raise ForecastError("yfinance is not installed; install with .[forecast].") from None

    ticker = ticker.upper().strip()
    quote_price: float | None = None
    quote_currency = "USD"
    history_closes: list[float] = []
    history_dates: list[str] = []
    news_titles: list[str] = []
    calendar_summary = ""

    try:
        t = yf.Ticker(ticker)
    except Exception as exc:  # noqa: BLE001
        LOG.warning("yfinance.Ticker(%s) failed: %s", ticker, exc)
        return ForecastFacts(
            ticker=ticker,
            quote_price=None,
            quote_currency="USD",
            history_closes=[],
            history_dates=[],
            news_titles=[],
            calendar_summary="",
        )

    # Quote (latest close).
    try:
        hist = t.history(period="2d", auto_adjust=False)
        if hist is not None and not hist.empty:
            quote_price = float(hist["Close"].iloc[-1])
        if hasattr(t, "fast_info"):
            quote_currency = (t.fast_info.get("currency") or "USD") if t.fast_info else "USD"
    except Exception as exc:  # noqa: BLE001
        LOG.warning("quote fetch failed for %s: %s", ticker, exc)

    # Daily history.
    try:
        period = f"{max(lookback_days + 5, 30)}d"
        long_hist = t.history(period=period, auto_adjust=True)
        if long_hist is not None and not long_hist.empty:
            tail = long_hist.tail(lookback_days)
            history_closes = [float(c) for c in tail["Close"].tolist()]
            history_dates = [d.strftime("%Y-%m-%d") for d in tail.index]
    except Exception as exc:  # noqa: BLE001
        LOG.warning("history fetch failed for %s: %s", ticker, exc)

    # News headlines (yfinance returns a list of dicts; shape varies by version).
    try:
        news = getattr(t, "news", []) or []
        for item in news[:8]:
            title = (
                item.get("title")
                or (item.get("content") or {}).get("title")
                or ""
            )
            if title:
                news_titles.append(str(title).strip())
    except Exception as exc:  # noqa: BLE001
        LOG.warning("news fetch failed for %s: %s", ticker, exc)

    # Calendar / next earnings (best-effort string summary).
    try:
        cal = getattr(t, "calendar", None)
        if cal is not None:
            if hasattr(cal, "to_dict"):
                calendar_summary = json.dumps(
                    {k: str(v) for k, v in cal.to_dict().items()}, default=str
                )[:600]
            elif isinstance(cal, dict):
                calendar_summary = json.dumps({k: str(v) for k, v in cal.items()})[:600]
    except Exception as exc:  # noqa: BLE001
        LOG.warning("calendar fetch failed for %s: %s", ticker, exc)

    return ForecastFacts(
        ticker=ticker,
        quote_price=quote_price,
        quote_currency=quote_currency,
        history_closes=history_closes,
        history_dates=history_dates,
        news_titles=news_titles,
        calendar_summary=calendar_summary,
    )


# ---------------------------------------------------------------------------
# Prompt assembly
# ---------------------------------------------------------------------------


def build_prompt(facts: ForecastFacts) -> str:
    """Assemble the user message from gathered facts.

    Keeps the prompt compact — just the facts, no commentary. The system
    prompt does the heavy lifting on the analyst persona and rules.
    """
    parts = [f"Ticker: {facts.ticker}"]
    if facts.has_quote:
        parts.append(f"Latest quote: {facts.quote_price:.2f} {facts.quote_currency}")
    else:
        parts.append("Latest quote: unavailable")

    if facts.has_history:
        closes = ", ".join(f"{c:.2f}" for c in facts.history_closes)
        parts.append(
            f"Last {len(facts.history_closes)} trading-day closes (oldest first): {closes}"
        )
    else:
        parts.append("Recent close history: unavailable")

    if facts.calendar_summary:
        parts.append(f"Calendar / earnings: {facts.calendar_summary}")
    else:
        parts.append("Calendar / earnings: not in data feed")

    if facts.news_titles:
        bullets = "\n".join(f"- {t}" for t in facts.news_titles)
        parts.append(f"Recent headlines:\n{bullets}")
    else:
        parts.append("Recent headlines: none retrieved")

    parts.append(
        "Submit your forecast by calling the submit_forecast tool. Do not "
        "respond with free text."
    )
    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# LLM call
# ---------------------------------------------------------------------------


def _extract_tool_call(content: list[Any]) -> dict[str, Any]:
    """Find the submit_forecast tool_use block in the response content."""
    for block in content:
        block_type = getattr(block, "type", None)
        if block_type == "tool_use" and getattr(block, "name", None) == "submit_forecast":
            return dict(block.input)
    raise ForecastError("Model did not call the submit_forecast tool.")


def _validate_forecast(payload: dict[str, Any]) -> None:
    """Belt-and-braces invariant check on the tool input.

    The API enforces shape; this catches semantic mistakes (e.g. low > high).
    """
    required = {"low", "base", "high", "catalysts", "action", "confidence", "premortem"}
    missing = required - payload.keys()
    if missing:
        raise ForecastError(f"Forecast missing required fields: {sorted(missing)}")
    low, base, high = float(payload["low"]), float(payload["base"]), float(payload["high"])
    if not (low <= base <= high):
        raise ForecastError(f"Forecast invariant violated: low={low}, base={base}, high={high}")
    catalysts = payload["catalysts"]
    if not isinstance(catalysts, list) or len(catalysts) != 3:
        raise ForecastError(f"Forecast 'catalysts' must be a list of exactly 3, got {catalysts!r}")
    if payload["action"] not in {"BUY", "HOLD", "TRIM"}:
        raise ForecastError(f"Forecast 'action' must be BUY/HOLD/TRIM, got {payload['action']!r}")
    if payload["confidence"] not in {"Low", "Medium", "High"}:
        raise ForecastError(
            f"Forecast 'confidence' must be Low/Medium/High, got {payload['confidence']!r}"
        )


def forecast(
    ticker: str,
    *,
    model: str | None = None,
    client: Any | None = None,
    facts: ForecastFacts | None = None,
) -> ForecastResult:
    """Generate a one-week forecast for ``ticker``.

    Args:
        ticker: Symbol to forecast. Case-insensitive.
        model: Override ``ANTHROPIC_MODEL`` env / default.
        client: Optional pre-built ``anthropic.Anthropic`` client (tests).
        facts: Pre-gathered facts (tests). When omitted, calls ``gather_facts``.

    Raises:
        ForecastUnavailable: if ``ANTHROPIC_API_KEY`` is not set.
        ForecastError: on network / API / schema failures.
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key and client is None:
        raise ForecastUnavailable(
            "ANTHROPIC_API_KEY is not set. Add it to Streamlit Cloud secrets "
            "or set it locally to enable the Forecast page."
        )

    if client is None:
        try:
            import anthropic
        except ImportError as exc:
            raise ForecastError(
                "anthropic SDK not installed; reinstall with .[forecast]."
            ) from exc
        client = anthropic.Anthropic(api_key=api_key)

    chosen_model = model or DEFAULT_MODEL
    facts = facts if facts is not None else gather_facts(ticker)
    user_prompt = build_prompt(facts)

    # The system prompt is small (~500 tokens) and on Haiku 4.5 the minimum
    # cacheable prefix is 4096 tokens, so cache_control here is best-effort —
    # it kicks in if you swap to Opus or extend the system prompt later.
    system_blocks = [
        {"type": "text", "text": SYSTEM_PROMPT, "cache_control": {"type": "ephemeral"}}
    ]
    try:
        # The Anthropic SDK has very strict typed overloads for `tools`;
        # our schema is statically valid, but mypy can't unify the dict
        # literal against the dozen-variant union. The runtime call is
        # exactly what the SDK accepts.
        response = client.messages.create(  # type: ignore[call-overload]
            model=chosen_model,
            max_tokens=DEFAULT_MAX_TOKENS,
            system=system_blocks,
            tools=[FORECAST_TOOL],
            tool_choice={"type": "tool", "name": "submit_forecast"},
            messages=[{"role": "user", "content": user_prompt}],
        )
    except Exception as exc:  # noqa: BLE001
        LOG.warning("Anthropic API call failed for %s: %s", ticker, exc)
        raise ForecastError(f"Anthropic API call failed: {exc}") from exc

    payload = _extract_tool_call(response.content)
    _validate_forecast(payload)

    usage = getattr(response, "usage", None)
    raw_usage = (
        {
            "input_tokens": getattr(usage, "input_tokens", 0),
            "output_tokens": getattr(usage, "output_tokens", 0),
            "cache_read_input_tokens": getattr(usage, "cache_read_input_tokens", 0),
            "cache_creation_input_tokens": getattr(usage, "cache_creation_input_tokens", 0),
        }
        if usage is not None
        else {}
    )

    return ForecastResult(
        ticker=facts.ticker,
        low=float(payload["low"]),
        base=float(payload["base"]),
        high=float(payload["high"]),
        catalysts=list(payload["catalysts"]),
        action=str(payload["action"]),
        confidence=str(payload["confidence"]),
        premortem=str(payload["premortem"]),
        asof_utc=datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        model=chosen_model,
        raw_usage=raw_usage,
    )


def forecast_age(asof_utc: str) -> timedelta:
    """How long ago was this forecast generated?"""
    try:
        gen = datetime.strptime(asof_utc, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=UTC)
    except ValueError:
        return timedelta(0)
    return datetime.now(UTC) - gen
